/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    getBoardState
 * Signature: ()[[I
 */
JNIEXPORT jobjectArray JNICALL Java_Main_getBoardState
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    movePiece
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_Main_movePiece
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
